-- +goose Up
ALTER TABLE books
    ALTER COLUMN title TYPE VARCHAR(255),
    ALTER COLUMN title SET NOT NULL,
    ALTER COLUMN author TYPE VARCHAR(100),
    ALTER COLUMN author SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN name TYPE VARCHAR(50),
    ALTER COLUMN name SET NOT NULL;
ALTER TABLE users
    ALTER COLUMN email TYPE VARCHAR(255),
    ALTER COLUMN email SET NOT NULL;
ALTER TABLE users
    ADD CONSTRAINT name_unique UNIQUE (name);

-- +goose Down
ALTER TABLE books
    ALTER COLUMN title TYPE TEXT,
    ALTER COLUMN author TYPE TEXT;
